export type Municipio = string;

export type Departamento = string;

export const departamentosMunicipios: Record<Departamento, Municipio[]> = {
  Guatemala: [
    'Guatemala',
    'Santa Catarina Pinula',
    'San José Pinula',
    'San José del Golfo',
    'Palencia',
    'Chinautla',
    'San Pedro Ayampuc',
    'Mixco',
    'San Pedro Sacatepéquez',
    'San Juan Sacatepéquez',
    'San Raymundo',
    'Chuarrancho',
    'Fraijanes',
    'Amatitlán',
    'Villa Nueva',
    'Villa Canales',
    'Petapa',
  ],
  'El Progreso': [
    'Guastatoya',
    'Morazán',
    'Sanarate',
    'Sansare',
    'San Agustín Acasaguastlán',
    'San Antonio La Paz',
    'San Cristóbal Acasaguastlán',
    'El Jícaro',
  ],
  Sacatepéquez: [
    'Antigua Guatemala',
    'Pastores',
    'Jocotenango',
    'Sumpango',
    'Santo Domingo Xenacoj',
    'Santiago Sacatepéquez',
    'San Lucas Sacatepéquez',
    'Magdalena Milpas Altas',
    'Santa María de Jesús',
    'San Bartolomé Milpas Altas',
    'Santa Lucía Milpas Altas',
    'San Miguel Dueñas',
    'Ciudad Vieja',
    'Alotenango',
    'San Antonio Aguas Calientes',
    'Santa Catarina Barahona',
  ],
  Chimaltenango: [
    'Chimaltenango',
    'San José Poaquil',
    'San Martín Jilotepeque',
    'San Juan Comalapa',
    'Santa Apolonia',
    'Tecpán Guatemala',
    'Patzún',
    'Pochuta',
    'Patzicía',
    'Santa Cruz Balanyá',
    'Yepocapa',
    'San Andrés Itzapa',
    'Parramos',
    'Zaragoza',
    'El Tejar',
    'Acatenango',
  ],
  Escuintla: [
    'Escuintla',
    'Santa Lucía Cotzumalguapa',
    'La Democracia',
    'Siquinalá',
    'Masagua',
    'Tiquisate',
    'La Gomera',
    'Guanagazapa',
    'San José',
    'Iztapa',
    'Palín',
    'San Vicente Pacaya',
    'Nueva Concepción',
    'Sipacate',
  ],
  'Santa Rosa': [
    'Cuilapa',
    'Casillas',
    'Nueva Santa Rosa',
    'Oratorio',
    'San Juan Tecuaco',
    'Chiquimulilla',
    'Taxisco',
    'Santa María Ixhuatán',
    'Guanagazapa',
    'San Rafael Las Flores',
    'Barberena',
    'Pueblo Nuevo Viñas',
    'Santa Cruz Naranjo',
    'Santa Rosa de Lima',
  ],
  Sololá: [
    'Sololá',
    'Concepción',
    'San Andrés Semetabaj',
    'Panajachel',
    'Santa Catarina Palopó',
    'San Antonio Palopó',
    'San Lucas Tolimán',
    'Santa Cruz La Laguna',
    'San Pablo La Laguna',
    'San Marcos La Laguna',
    'San Juan La Laguna',
    'San Pedro La Laguna',
    'Santiago Atitlán',
    'Nahualá',
    'Santa Clara La Laguna',
    'Santa Lucía Utatlán',
    'San José Chacayá',
    'Santa María Visitación',
    'Santa Catarina Ixtahuacán',
  ],
  Totonicapán: [
    'Totonicapán',
    'San Cristóbal Totonicapán',
    'San Francisco El Alto',
    'San Andrés Xecul',
    'Momostenango',
    'Santa María Chiquimula',
    'Santa Lucía La Reforma',
    'San Bartolo Aguas Calientes',
  ],
  Quetzaltenango: [
    'Quetzaltenango',
    'Salcajá',
    'Olintepeque',
    'San Carlos Sija',
    'Sibilia',
    'Cabricán',
    'Cajolá',
    'San Miguel Siguilá',
    'San Juan Ostuncalco',
    'Concepción Chiquirichapa',
    'San Martín Sacatepéquez',
    'Almolonga',
    'Cantel',
    'Huitán',
    'Zunil',
    'Colomba',
    'San Francisco La Unión',
    'El Palmar',
    'Coatepeque',
    'Génova',
    'Flores Costa Cuca',
    'La Esperanza',
    'Palestina de Los Altos',
    'San Mateo',
  ],
  Suchitepéquez: [
    'Mazatenango',
    'Cuyotenango',
    'San Francisco Zapotitlán',
    'San Bernardino',
    'San José El Ídolo',
    'Santo Domingo Suchitepéquez',
    'San Lorenzo',
    'Samayac',
    'San Pablo Jocopilas',
    'San Antonio Suchitepéquez',
    'San Miguel Panán',
    'Río Bravo',
    'Pueblo Nuevo',
    'Santa Bárbara',
    'Patulul',
    'Chicacao',
    'San Juan Bautista',
    'Santo Tomás La Unión',
  ],
  Retalhuleu: [
    'Retalhuleu',
    'San Sebastián',
    'Santa Cruz Muluá',
    'San Martín Zapotitlán',
    'San Felipe',
    'Champerico',
    'Nuevo San Carlos',
    'El Asintal',
    'San Andrés Villa Seca',
  ],
  'San Marcos': [
    'San Marcos',
    'San Pedro Sacatepéquez',
    'Malacatán',
    'Ayutla',
    'Catarina',
    'Ocós',
    'San Pablo',
    'El Tumbador',
    'San Rafael Pie de La Cuesta',
    'Nuevo Progreso',
    'San Miguel Ixtahuacán',
    'Comitancillo',
    'San Lorenzo',
    'Tejutla',
    'Sipacapa',
    'Esquipulas Palo Gordo',
    'Río Blanco',
    'Tacaná',
    'Sibinal',
    'Ixchiguán',
    'Concepción Tutuapa',
    'San Cristóbal Cucho',
    'San José Ojetenam',
    'El Quetzal',
    'La Reforma',
    'Pajapita',
    'San Sebastián',
  ],
  Huehuetenango: [
    'Huehuetenango',
    'Chiantla',
    'Malacatancito',
    'Cuilco',
    'Nentón',
    'San Pedro Necta',
    'Jacaltenango',
    'Soloma',
    'San Ildefonso Ixtahuacán',
    'San Sebastián Coatán',
    'Barillas',
    'Aguacatán',
    'San Rafael La Independencia',
    'Todos Santos Cuchumatán',
    'San Juan Atitán',
    'Santa Eulalia',
    'San Mateo Ixtatán',
    'Colotenango',
    'San Sebastián',
    'Santiago Chimaltenango',
    'La Libertad',
    'San Miguel Acatán',
    'San Gaspar Ixchil',
    'Santa Ana Huista',
    'Unión Cantinil',
    'La Democracia',
    'Concepción Huista',
    'Petatan',
    'Tectitán',
  ],
  Quiché: [
    'Santa Cruz del Quiché',
    'Chiché',
    'Chinique',
    'Zacualpa',
    'Chajul',
    'Nebaj',
    'Cunén',
    'Uspantán',
    'San Pedro Jocopilas',
    'Chichicastenango',
    'Patzité',
    'San Antonio Ilotenango',
    'San Andrés Sajcabajá',
    'San Bartolomé Jocotenango',
    'Canillá',
    'Chicamán',
    'Pachalum',
    'Ixcán',
    'Patzité',
  ],
  'Baja Verapaz': [
    'Salamá',
    'San Miguel Chicaj',
    'San Jerónimo',
    'El Chol',
    'Rabinal',
    'Cubulco',
    'Granados',
    'Purulhá',
  ],
  'Alta Verapaz': [
    'Cobán',
    'San Pedro Carchá',
    'San Juan Chamelco',
    'San Cristóbal Verapaz',
    'Tactic',
    'Tamahú',
    'Tucurú',
    'Patzité',
    'Senahú',
    'Cahabón',
    'Lanquín',
    'Chisec',
    'Fray Bartolomé de Las Casas',
    'Chahal',
    'Pancajché',
    'Santa Cruz Verapaz',
    'La Tinta',
    'Raxruhá',
  ],
  Petén: [
    'Flores',
    'San Benito',
    'La Libertad',
    'San Francisco',
    'San Andrés',
    'San José',
    'Melchor de Mencos',
    'Poptún',
    'Dolores',
    'San Luis',
    'Sayaxché',
    'Santa Ana',
    'Las Cruces',
    'San Luis',
  ],
  Izabal: ['Puerto Barrios', 'Livingston', 'El Estor', 'Morales', 'Los Amates'],
  Zacapa: [
    'Zacapa',
    'Estanzuela',
    'Río Hondo',
    'Gualán',
    'La Unión',
    'Huité',
    'Cabañas',
    'Teculután',
    'Usumatlán',
    'San Jorge',
  ],
  Chiquimula: [
    'Chiquimula',
    'San José La Arada',
    'San Juan Ermita',
    'Olopa',
    'Esquipulas',
    'Concepción Las Minas',
    'Quezaltepeque',
    'Jocotán',
    'Camotán',
    'San Jacinto',
    'Ipala',
  ],
  Jalapa: [
    'Jalapa',
    'San Pedro Pinula',
    'San Luis Jilotepeque',
    'San Manuel Chaparrón',
    'San Carlos Alzatate',
    'Monjas',
    'Mataquescuintla',
  ],
  Jutiapa: [
    'Jutiapa',
    'El Progreso',
    'Santa Catarina Mita',
    'Comapa',
    'Jalpatagua',
    'Conguaco',
    'Moyuta',
    'Pasaco',
    'San José Acatempa',
    'Zapotitlán',
    'Agua Blanca',
    'Atescatempa',
    'Jerez',
    'Yupiltepeque',
    'El Adelanto',
    'Quesada',
  ],
};